server:
  host: 0.0.0.0
  port: 8805

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "61324"
  name: "vitalem_db"
  sslmode: "disable"

notification:
  url: "http://notification_service:8806/api/v1"

logger:
  level: "info"     # "debug", "info", "warn", "error"
  service_url: "http://logger_service:8802"
  service_name: "calendar_service"

jwt:
  secret: "4324pkh23sk4jh342alhdlfl2sdjf"
