version: '3.8'

services:
  # PostgreSQL - основная реляционная БД для хранения данных всех сервисов
  # Единый инстанс для всех микросервисов для упрощения разработки
  # В проде можно будет разделить на отдельные инстансы по сервисам
  postgres:
    image: postgres:15-alpine
    container_name: vitalem_postgres
    environment:
      POSTGRES_PASSWORD: 61324
      POSTGRES_USER: postgres
      POSTGRES_DB: vitalem_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M

  # RabbitMQ - брокер сообщений для асинхронного взаимодействия между сервисами
  # Используем для событийно-ориентированной коммуникации (event-driven)
  # Например: создание пользователя -> создание профиля пациента/врача
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: vitalem_rabbitmq
    ports:
      - "5672:5672"   # AMQP порт для сервисов
      - "15672:15672" # Management UI порт для админки (guest/guest)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M

  # ELK-стек для централизованного логирования и мониторинга
  # Elasticsearch - NoSQL БД для хранения и индексации логов
  # Движок для полнотекстового поиска и аналитики по логам
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms64m -Xmx64m"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M

  # Kibana - веб-интерфейс для Elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - NODE_OPTIONS="--max-old-space-size=128"
      - ELASTICSEARCH_REQUEST_TIMEOUT=30000
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M

  # Filebeat - агент для сбора и отправки логов
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    depends_on:
      - elasticsearch
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 64M

  # Logger Service - кастомный сервис для централизованного логирования
  # Принимает логи от всех микросервисов через REST API
  # Обогащает и сохраняет в Elasticsearch для последующего анализа
  logger_service:
    build:
      context: ./logger_service
      dockerfile: Dockerfile
    container_name: logger_service
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LOG_LEVEL=info
    ports:
      - "8802:8802"
    depends_on:
      - elasticsearch
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 64M

  # Identity Service - сервис аутентификации и управления пользователями
  # Отвечает за регистрацию, логин, JWT-токены и управление профилями юзеров
  # Первый сервис в цепочке взаимодействия с системой
  identity_service:
    build:
      context: ./identity_service
      dockerfile: Dockerfile
    container_name: identity_service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=61324
      - DB_NAME=vitalem_db
      - DB_SSL_MODE=disable
      - LOGGER_SERVICE_URL=http://logger_service:8802
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=guest
      - RMQ_PASS=guest
      - RMQ_EXCHANGE=vitalem
      - JWT_SECRET=4324pkh23sk4jh342alhdlfl2sdjf
      - LOG_LEVEL=info
    ports:
      - "8801:8801"
    depends_on:
      - postgres
      - rabbitmq
      - logger_service
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 64M

  # Specialist Service - сервис для работы с врачами/специалистами
  # Хранит профили врачей, специализации, расписания и т.д.
  # Интегрируется с другими сервисами через RabbitMQ и прямые HTTP-вызовы
  specialist_service:
    build:
      context: ./specialist_service
      dockerfile: Dockerfile
    container_name: specialist_service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=61324
      - DB_NAME=vitalem_db
      - DB_SSL_MODE=disable
      - LOGGER_SERVICE_URL=http://logger_service:8802
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=guest
      - RMQ_PASS=guest
      - RMQ_EXCHANGE=vitalem
      - JWT_SECRET=4324pkh23sk4jh342alhdlfl2sdjf
      - LOG_LEVEL=info
    ports:
      - "8803:8803"
    depends_on:
      - postgres
      - rabbitmq
      - logger_service
      - identity_service
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 64M

  # Patient Service - сервис для работы с пациентами
  # Хранит медицинские профили, историю болезней, рецепты и т.д.
  # Основной сервис для пользователей-пациентов системы
  patient_service:
    build:
      context: ./patient_service
      dockerfile: Dockerfile
    container_name: patient_service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=61324
      - DB_NAME=vitalem_db
      - DB_SSL_MODE=disable
      - LOGGER_SERVICE_URL=http://logger_service:8802
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=guest
      - RMQ_PASS=guest
      - RMQ_EXCHANGE=vitalem
      - JWT_SECRET=4324pkh23sk4jh342alhdlfl2sdjf
      - LOG_LEVEL=info
    ports:
      - "8804:8804"
    depends_on:
      - postgres
      - rabbitmq
      - logger_service
      - identity_service
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 64M
    
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data:
  rabbitmq_data: