server:
  host: 0.0.0.0
  port: 8806
  read_timeout: 10s
  write_timeout: 10s

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "61324"
  name: "vitalem_db"
  sslmode: "disable"

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"

logger:
  level: "info"     # "debug", "info", "warn", "error"
  service_url: "http://logger_service:8802"
  service_name: "notification_service"

jwt:
  secret: "4324pkh23sk4jh342alhdlfl2sdjf"

email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 465
  smtp_username: "asylknazbaj@gmail.com"
  smtp_password: "fsmi gwrw cdso pufr"
  smtp_from: "Notification Service <asylknazbaj@gmail.com>"

telegram:
  bot_token: "8134913914:AAG51fnF2uuIn9go3JEXQKcUEy9smDR5Bpg"
  chat_id: "-4705009453"

auth:
  jwt_secret: "4324pkh23sk4jh342alhdlfl2sdjf"
  code_ttl_seconds: 300
