server:
  host: 0.0.0.0
  port: 8801 # Port for the identity_service

database:
  db_host: postgres
  db_port: 5432
  db_user: postgres
  db_pass: 61324
  db_name: vitalem_db
  db_ssl_mode: disable

jwt:
  jwt_secret: 4324pkh23sk4jh342alhdlfl2sdjf
  jwt_expire: 24

logging:
  console_level: error  # Только ошибки будут выводиться в консоль
  service_level: info   # Все информационные сообщения будут отправляться в logger_service
  service_url: http://logger_service:8802